#!/bin/bash

# Custom Keybindings :

bind '"\C-x"':"\" clear \C-m\""

# Colours :

# Reset
export nc='\033[0m'       # Text Reset

# Regular Colors
export black='\033[0;30m'        # Black
export red='\033[0;31m'          # Red
export green='\033[0;32m'        # Green
export yellow='\033[0;33m'       # Yellow
export blue='\033[0;34m'         # Blue
export purple='\033[0;35m'       # Purple
export cyan='\033[0;36m'         # Cyan
export white='\033[0;37m'        # White

# Bold
export bblack='\033[1;30m'       # Black
export rred='\033[1;31m'         # Red
export ggreen='\033[1;32m'       # Green
export yyellow='\033[1;33m'      # Yellow
export bblue='\033[1;34m'        # Blue
export ppurple='\033[1;35m'      # Purple
export ccyan='\033[1;36m'        # Cyan
export wwhite='\033[1;37m'       # White

# Underline
export ublack='\033[4;30m'       # Black
export ured='\033[4;31m'         # Red
export ugreen='\033[4;32m'       # Green
export uyellow='\033[4;33m'      # Yellow
export ublue='\033[4;34m'        # Blue
export upurple='\033[4;35m'      # Purple
export ucyan='\033[4;36m'        # Cyan
export uwhite='\033[4;37m'       # White

# Background
export bgblack='\033[40m'       # Black
export bgred='\033[41m'         # Red
export bggreen='\033[42m'       # Green
export bgyellow='\033[43m'      # Yellow
export bgblue='\033[44m'        # Blue
export bgpurple='\033[45m'      # Purple
export bgcyan='\033[46m'        # Cyan
export bgwhite='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

